### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yuqimiao** [stephenslab/susiF.alpha#2]
I got the following error message using the recommended installation:

<img width="1380" alt="image" src="https://user-images.githubusercontent.com/54858144/154357152-8576abf9-d948-473c-843c-8abd7c82031e.png">

Thank you for your help!

Yuqi

**Comment by pcarbo** [comment]
Yes we are aware of this issue, but it should just be treated as a warning, and should not prevent you from installing the package.

What is your setting for "warn"?

```r
options("warn")
```

**Comment by yuqimiao** [comment]
It's like this:

```
> options("warn")
$warn
[1] 0
```

**Comment by pcarbo** [comment]
Hi Yuqi, can you try again? I've removed the help page causing the issue.

**Comment by yuqimiao** [comment]
It works!! Thank you!
