### ISSUE TITLE
Inconsistent S3 methods

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/susiF.alpha#4]
@william-denault The S3 methods you define have to be consistent in the names of the input arguments (the more specific method should always inherit the input arguments of the less specific method). These are the problematic functions (most of which appear to be easy to fix):

```
* checking S3 generic/method consistency ... WARNING
cal_partial_resid:
  function(susiF.obj, l, X, D, C, indx_lst, ...)
cal_partial_resid.EBmvFR:
  function(EBmvFR.obj, l, X, D, C, indx_lst, ...)

cal_partial_resid:
  function(susiF.obj, l, X, D, C, indx_lst, ...)
cal_partial_resid.EBmvFR:
  function(EBmvFR.obj, l, X, D, C, indx_lst, ...)

estimate_residual_variance:
  function(susiF.obj, Y, X, ...)
estimate_residual_variance.EBmvFR:
  function(EBmvFR.obj, Y, X, ...)

estimate_residual_variance:
  function(susiF.obj, Y, X, ...)
estimate_residual_variance.EBmvFR:
  function(EBmvFR.obj, Y, X, ...)

get_ER2:
  function(susiF.obj, Y, X, ...)
get_ER2.EBmvFR:
  function(EBmvFR.obj, Y, X, ...)

get_ER2:
  function(susiF.obj, Y, X, ...)
get_ER2.EBmvFR:
  function(EBmvFR.obj, Y, X, ...)

HMM_regression:
  function(susiF.obj, Y, X, verbose, maxit, fit_indval, ...)
HMM_regression.susiF:
  function(susiF.obj, Y, X, verbose, fit_indval)

HMM_regression:
  function(susiF.obj, Y, X, verbose, maxit, fit_indval, ...)
HMM_regression.susiF:
  function(susiF.obj, Y, X, verbose, fit_indval)

log_BF:
  function(G_prior, Bhat, Shat, lowc_wc, df, ...)
log_BF.mixture_normal_per_scale:
  function(G_prior, Bhat, Shat, lowc_wc, indx_lst, df, ...)

log_BF:
  function(G_prior, Bhat, Shat, lowc_wc, df, ...)
log_BF.mixture_normal_per_scale:
  function(G_prior, Bhat, Shat, lowc_wc, indx_lst, df, ...)

out_prep:
  function(susiF.obj, Y, X, indx_lst, filter.cs, outing_grid, ...)
out_prep.EBmvFR:
  function(EBmvFR.obj, X, indx_lst, outing_grid, ...)

out_prep:
  function(susiF.obj, Y, X, indx_lst, filter.cs, outing_grid, ...)
out_prep.EBmvFR:
  function(EBmvFR.obj, X, indx_lst, outing_grid, ...)

test_stop_cond:
  function(susiF.obj, check, cal_obj, Y, X, D, C, indx_lst, ...)
test_stop_cond.EBmvFR:
  function(EBmvFR.obj, check, cal_obj, Y, X, D, C, indx_lst, ...)

test_stop_cond:
  function(susiF.obj, check, cal_obj, Y, X, D, C, indx_lst, ...)
test_stop_cond.EBmvFR:
  function(EBmvFR.obj, check, cal_obj, Y, X, D, C, indx_lst, ...)

TI_regression:
  function(susiF.obj, Y, X, verbose, filter.number, family, ...)
TI_regression.susiF:
  function(susiF.obj, Y, X, verbose, filter.number, family)

TI_regression:
  function(susiF.obj, Y, X, verbose, filter.number, family, ...)
TI_regression.susiF:
  function(susiF.obj, Y, X, verbose, filter.number, family)

update_cal_fit_func:
  function(susiF.obj, Y, X, indx_lst, TI, HMM, filter.number, family,
           ...)
update_cal_fit_func.EBmvFR:
  function(EBmvFR.obj, indx_lst, ...)

update_cal_fit_func:
  function(susiF.obj, Y, X, indx_lst, TI, HMM, filter.number, family,
           ...)
update_cal_fit_func.EBmvFR:
  function(EBmvFR.obj, indx_lst, ...)

update_lfsr_effect:
  function(susiF.obj, ...)
update_lfsr_effect.susiF:
  function(susiF.obj)

update_lfsr_effect:
  function(susiF.obj, ...)
update_lfsr_effect.susiF:
  function(susiF.obj)

update_residual_variance:
  function(susiF.obj, sigma2, ...)
update_residual_variance.EBmvFR:
  function(EBmvFR.obj, sigma2)

update_residual_variance:
  function(susiF.obj, sigma2, ...)
update_residual_variance.EBmvFR:
  function(EBmvFR.obj, sigma2)
```

**Comment by william-denault** [comment]
I will fix that in the coming days. 

How would you fix the first example?
`cal_partial_resid:
  function(susiF.obj, l, X, D, C, indx_lst, ...)
cal_partial_resid.EBmvFR:
  function(EBmvFR.obj, l, X, D, C, indx_lst, ...)
`

Would simply change it as

`cal_partial_resid:
  function( obj, l, X, D, C, indx_lst, ...)
cal_partial_resid.EBmvFR:
  function( obj, l, X, D, C, indx_lst, ...)
`
?

**Comment by pcarbo** [comment]
@william-denault The only issue with the first one is the first argument. So for example this would work:

```
cal_partial_resid:
  function(obj, l, X, D, C, indx_lst, ...)
cal_partial_resid.EBmvFR:
  function(obj, l, X, D, C, indx_lst, ...)
```

In most cases the simplest solution is to have the exact same inputs (even if some of those inputs do nothing).

**Comment by william-denault** [comment]
Hello @pcarbo 
Do you know how to generate the documentation for the S3 method 

In susiF.alpha I describe the argument for the generic but the method may have more argument in some other context. Do you know how to deal with that  (see an example below)




`

#' @title Update susiF by computing posterior curves
#
#' @param  obj a susiF/EBmvFR object defined by init_susiF_obj function
#' @param Y  functional phenotype, matrix of size N by size J. The underlying algorithm uses wavelet which assume that J is of the form J^2. If J not a power of 2, susif internally remaps the data into grid of length 2^J
#
#' @param X matrix of size n by p in
#
#' @param indx_lst list generated by gen_wavelet_indx for the given level of resolution
#' @param TI logical if set to true use cycle spinning wavelet regression
#'@param filter.number see documentation of wd from wavethresh package
#'@param family see documentation of wd from wavethresh package
#' @return susiF object
#
#' @export
#' @keywords internal
update_cal_fit_func  <- function( obj, indx_lst,  ...)
  UseMethod("update_cal_fit_func")

#' @rdname update_cal_fit_func
#
#' @method update_cal_fit_func susiF
#
#' @export update_cal_fit_func.susiF
#
#' @importFrom wavethresh wr
#
#' @importFrom wavethresh wd
#
#' @export
#' @keywords internal

update_cal_fit_func.susiF <- function(obj,
                                      Y,
                                      X,
                                      indx_lst,
                                      TI=TRUE,
                                      HMM=FALSE,
                                      filter.number = 10,
                                      family = "DaubLeAsymm" ,...)
{`

**Comment by william-denault** [comment]
I fixed this issue
